services:
  - type: web
    name: line-running-consultation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -c gunicorn.conf.py"
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /health/
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true 